IBM/unitxt

src/unitxt/templates.py
Avoid including Input: and Output:
Needed for starcoder.
=> Changed default rendering template

prepare/processors/to_string.py, src/unitxt/blocks.py, src/unitxt/catalog/processors/to_string_stripped.json, src/unitxt/metric.py, src/unitxt/processors.py, src/unitxt/schema.py, src/unitxt/templates.py, tests/test_templates.py
Added a to_string_splitted preprocessor
Changed default uses of of to_string to to_string_splitted Added a test for the standard input output template
Signed-off-by: Yoav Katz <katz@il.ibm.com>
=> Changed default behavior to strip string

src/unitxt/metrics.py, tests/test_metrics.py
When no classes were in references, threw an exception instead. Now returns Nan.
When only one class was in references, scikitlearn f1 incorrectly iterpreted the input as two classes.  Added a flag to avoid this behavior.
Added unit text to fix it.
=> Fixed F1 in multi label

src/unitxt/dataset.py, src/unitxt/operators.py, src/unitxt/renderers.py, src/unitxt/schema.py, tests/test_operators.py, tests/test_recipe.py
The new renderer sometimes tried to process the same instance twice which caused an error
=> BugFix: avoid processing the same instance twice

src/unitxt/formats.py, tests/test_formats.py
Which added "\n\n" when instruction is empty
Added unit text
=> Fix for empty_instruction case

prepare/templates/classification/choices/templates.py, requirements/tests.rqr, src/unitxt/catalog.py, src/unitxt/catalog/templates/classification/choices/simple2.json, src/unitxt/loaders.py, src/unitxt/operators.py, src/unitxt/standard.py, src/unitxt/test_utils/artifact.py, src/unitxt/test_utils/card.py, tests/test_loaders.py, tests/test_operators.py, tests/test_recipe.py
Added a env new variable called UNITEXT_IBM_COS_LOADER_LINE_LIMIT which is used to limit the number of lines downloaded from COS.  This is used to speedup generating datacards (using the prepare/cards/*.py files) .  
This works only for datsets that are in jsonl format.   
In another change avoid placing random file names in output
(To simplify diffs comparison)
=> Add load limit

prepare/cards/belebele.py, prepare/cards/boolq.py, prepare/cards/ethos.py, prepare/cards/mmlu.py, prepare/cards/sst2.py, prepare/cards/winogrande.py, prepare/cards/xnli.py, prepare/cards/xwinogrande.py, src/unitxt/metric.py, src/unitxt/operator.py, src/unitxt/recipe.py, src/unitxt/renderers.py, src/unitxt/splitters.py, src/unitxt/standard.py, src/unitxt/test_utils/card.py, tests/test_function_operators.py
Added debug_card utility to help debug cards
At the core, added an ability to run a sequence operator
only for a given number of steps.
The debug_card utility iterates over all steps in a card and
prints the for each step all the streams (splits) in the output
and the first example in each stream.
test_card(card,debug=True  )
=> Add debug card capabilities

src/unitxt/splitters.py
When using `DiverseLabelsSampler` the demos were selected using the first template.
For templates following the first template, this caused a mismatch between the templates used for the question and the demo.
The root cause was:
The DiverseLabelsSampler has a cache within self.labels, initialized [here](https://github.com/IBM/unitxt/blob/main/src/unitxt/splitters.py#L130). The cache is reset in [DiverseLabelsSampler.prepare()](https://github.com/IBM/unitxt/blob/main/src/unitxt/splitters.py#L110).
The issue is that Sampler.prepare() is not called for the [sampler](https://github.com/IBM/unitxt/blob/main/src/unitxt/splitters.py#L159) member within a SpreadSplit. It should be called from [SpreadSplit.prepare](https://github.com/IBM/unitxt/blob/main/src/unitxt/splitters.py#L161).
=> Fix demos selection using DiverseLabelsSampler

src/unitxt/templates.py, tests/test_templates.py
Change `YesNoTemplate` to accept a `class_field`, which contains the name of the field with the queried class_name. It is now expected in both the inputs and the outputs to the template.
This replaces the `class_name` parameter, that directly included the queried class name.
=> Updates to YesNoTemplate

src/unitxt/splitters.py, tests/test_splitters.py
Improve the error handling for the `DiverseLabelsSampler`.
The motivation behind is having set value set in the "choices" field, by mistake, to a string:
```
AddFields(
fields={
"class": "Termination for convenience",  #### The mistake is here, should be ["Termination for convenience"]
"text_type": "contractual sentence",
}
),
```
Since the code then iterates over the value in this field, the iteration was over the string characters, which is wrong. It was expected that "choices" within the input contains is a list. Added a check for that.
Also added other relevant tests and checks, including one that represents the issue.
=> improve error handling in DiverseLabelsSampler

prepare/formats/empty_input_output_separators.py, src/unitxt/catalog/formats/empty_input_output_separator.json
This is required for inference in 0-shot mode, when it is expected that the model completes the input, and does not answer in a new line.
=> A new format that does not have an input output seperator

src/unitxt/operators.py, tests/test_operators.py
In recent change, mapping of list was not supported .  This prevented valid uses cases such as mapping [] to ['None']/
This is a fix for this.
Also ensured that mapper values are deep copied to prevent overwritten .
=> Add support for mapping full list in MapInstanceValues

src/unitxt/metrics.py
This is done by  setting  the new `hf_additional_input_fields` parameter.
=> Allow adding additional inputs to HF metrics

src/unitxt/random_utils.py, src/unitxt/splitters.py, tests/test_random_utils.py
Added a new option to create random generators that depend only on the default seed and a provided sub seed.
Modify RandomSampler to use such random generators.
=> Support random generators that are independent of previous randomizations

src/unitxt/metric.py, src/unitxt/operators.py, src/unitxt/stream.py
In case this is worth the trouble, and/or backward compatible,
the correct verb here is `peek`, rather than `peak`:
https://www.merriam-webster.com/dictionary/peek
=> peek at the first instance

src/unitxt/splitters.py, tests/test_splitters.py
The class assumed there is only one output field which needs to be balanced, and took the first one.
This was not true for NER.  Added an explicit customizable field to select which output field should be used.
Also improved the tests.
=> DiverseLabelsSampler fix

src/unitxt/templates.py
Turns out that if you don't specify the type, you can not override the parameter.
=> Fix to allow override empty_label of multi_label template.

src/unitxt/operators.py, tests/test_operators.py
I missed it in the review, but the behavior was that the same suffix/prefix was repeat multiple times.
=> Fix suffix prefix not return same prefix/suffix repeated

src/unitxt/splitters.py
The line overwrites a value by mistake.
=> Removed variable set in debugging

prepare/cards/argument_topic.py, prepare/cards/claim_stance_topic.py
Found out that in Debater datasets there is no need to define random split.
=> fixing split definition for debater datatests

docs/docs/contributors_guide.rst, docs/index.rst
Add a new contributors guide, with a section describing how to create a new Unitxt release.
Closes https://github.com/IBM/unitxt/issues/438
=> Document release notes

prepare/cards/stsb.py, prepare/cards/xlsum.py, src/unitxt/catalog/cards/cola.json, src/unitxt/catalog/cards/dbpedia_14.json, src/unitxt/test_utils/card.py
Improved error messages of metrics checks in test_card
Added option to disable test_card by setting an environment variable  UNITXT_TEST_CARD_DISABLE
Updated json of dbpedia and cola - after running prepare
=> Improve test card error messages and allow disabling by env variable

src/unitxt/operators.py, tests/test_operators.py
It seems that the simple conditions, listed in `FilterByCondition` , can all be replaced by simple lambda conditions.  We can thus replace, and enjoy from additional, perhaps more involved, conditions that lambda can express. 
This also refers to [an issue](https://github.com/IBM/unitxt/issues/415) by @matanor
=> Add FilterByQuery and ExecuteQuery as simple operators receiving textual python query

src/unitxt/operators.py, tests/test_operators.py
to be employed just one step before metric evaluation
=> Add a new Perturbate operator that is handy for faking prediction as a perturbated version of target or for any other perturbation use cases

docs/catalog.py, docs/conf.py, src/unitxt/formats.py
For https://github.com/IBM/unitxt/issues/460
- Under a directory (e.g. cards) list the content of the dir
- Each artifact should be in a separate file
- Artifact type docstring will be under the artifact's json
=> Improve catalog UI on documentation website by separating catalog objects to files and adding information  per catalog item

prepare/cards/squad.py, prepare/templates/qa/contextual.py, src/unitxt/catalog/cards/squad.json, src/unitxt/catalog/templates/qa/contextual/simple.json, src/unitxt/catalog/templates/qa/contextual/simple2.json
Standardize QA templates to use `answer` as the output field and not `answers`.
Update squad card to use the standard QA task.
=> Update QA templates

Makefile, docs/catalog.py
Update catalog directory contents, to enable:
- The TOC panel on the left
- The breadcrumbs on the top
Also:
- This change avoids most of the warnings while creating the docs. 
- Fixed the length of the heading marker under the "Explanation for X" title, now its aligned with the title length.
To make this work, all the catalog RST files are now created in the main doc directory (i.e. not in subdirs), and their name is prefixed with `catalog.`.
=> Update catalog navigation Index on documentation side menu for easier catalog browsing

.gitignore, Makefile, docs/catalog.py
- Fix the name of the catalog main file: catalog.catalog.rst -> catalog.rst
- Update .gitignore to ignore all catalog rst files.
- Update makefile to clear docs/_build when running clear-docs. Otherwise old htmls may be shown by the server, thus preventing the contents from properly reflecting the RST files.
=> Fix catalog main entry

src/unitxt/test_utils/card.py, src/unitxt/test_utils/metrics.py
For quick check of catalog consistency
(Also made UNITXT_TEST_CARD_DISABLE effect load_examples_from_standard_recipe)
=> Added UNITXT_TEST_METRIC_DISABLE to disable test_metric

src/unitxt/split_utils.py
close https://github.com/IBM/unitxt/issues/529
To allow source name that starts with numeric, I replaced `[a-zA-Z]` to `\w` in regex.
I read [CONTRIBUTING.md](https://github.com/IBM/unitxt/blob/main/CONTRIBUTING.md) but I don't have the permission to create a branch so I forked this repo.
=> Fix parser to allow source name that starts with numeric

src/unitxt/loaders.py
By download to a temporary file and doing an atomic move.
=> Avoid race condition when download files to IBM COS cache

src/unitxt/artifact.py, src/unitxt/catalog.py, tests/test_artifact.py
- Add a new artifact_identifier field to Artifact
- Added tests
- Motivation: sometimes, given an Artifact, it is useful to know the identifier that for used for fetching the artifact from the catalog. So this PR saves that identifier within the artifact, when it is loaded from the catalog.
=> Support artifact_identifier in Artifact objects

src/unitxt/ui/load_catalog_data.py, src/unitxt/ui/run.py, src/unitxt/ui/ui_utils.py
Correct handling of private + unitxt catalog combo - private catalog overrides unitxt catalog
=> avoid duplicate values in UI

tests/test_operators.py
that entry was named  'just_for_testing' but it still remained there. 
Now the test does not generate any new entry in the catalog.
=> changed the test that generated a new entry in the catalog

prepare/cards/multidoc2dial.py, src/unitxt/artifact.py, src/unitxt/operators.py, src/unitxt/test_utils/card.py, tests/test_function_operators.py
Following Elron's fix, remove all special tweaks  to not import modules in init, and artificially postpone to process.  After Elron's fix, these tweaks are not needed.
=> Following Elron's fix, remove all special tweaks  

prepare/cards/hellaswag.py, prepare/metrics/precision_recall.py, prepare/processors/processors.py, prepare/templates/classification/classification.py, src/unitxt/catalog/cards/unfair_tos.json, src/unitxt/metrics.py, src/unitxt/test_utils/card.py, tests/library/test_metrics.py
The template is responsible for verbalization and hence it should deal with converting empty label list to 'none' and then from 'none' to an empty list in the post processor.
Until now the second part ('none' to empty list)  was handled in the metric, which complicates its code, and is error prone, in case a different verbalization is used (e.g. in other languages)
Also changed code card_test code to check metrics on ground truth and random predictions in all the templates and not only the last one as was before.
=> Fix classification code so multi-label metrics are not aware of 'none'

prepare/metrics/kendalltau.py, prepare/metrics/roc_auc.py, src/unitxt/catalog/metrics/kendalltau_b.json, src/unitxt/catalog/metrics/roc_auc.json, src/unitxt/eval_utils.py, src/unitxt/metrics.py, src/unitxt/operators.py, src/unitxt/type_utils.py, tests/library/test_metrics.py, tests/library/test_type_utils.py
1. Standard api for disabling/enabling confidence interval computation of metric/metricpipeline
2. make kendalltau and roc_auc metrics and not metric pipelines (to temporarily overcome the multiple metric pipeline issue)
=> Eval metrics

docs/catalog.py, docs/conf.py, docs/docs/saving_and_loading_from_catalog.rst, docs/index.rst, src/unitxt/__init__.py, src/unitxt/artifact.py, src/unitxt/catalog.py, src/unitxt/dataset.py, src/unitxt/dataset_utils.py, src/unitxt/metric.py, src/unitxt/parsing_utils.py, src/unitxt/register.py, src/unitxt/test_utils/catalog.py, tests/library/test_artifact.py, tests/library/test_artifact_recovery.py, tests/library/test_catalogs.py, tests/library/test_parsing_utils.py
This PR allows to specify artifact names with modifications. For example if you have `metrics.accuracy` in the catalog with a field `reduction="mean"` you can load it with a modification to median by: `metrics.accuracy[reduction=median]`
=> Add ability to load from catalog with arguments overwrite

docs/docs/adding_dataset.rst
Change the task and template artifact names to the correct names.
=> Docfix: Fix incorrect artifact names in Adding Dataset doc

.gitignore, prepare/cards/dart.py, prepare/cards/tablerow_classify.py, prepare/cards/wiki_bio.py, prepare/tasks/generation.py, prepare/templates/classification/classification.py, prepare/templates/generation/generation.py, src/unitxt/blocks.py, src/unitxt/catalog/cards/dart.json, src/unitxt/catalog/cards/tablerow_classify.json, src/unitxt/catalog/cards/wiki_bio.json, src/unitxt/catalog/tasks/generation.json, src/unitxt/catalog/templates/classification/multi_class/default.json, src/unitxt/catalog/templates/generation/all.json, src/unitxt/catalog/templates/generation/default.json, src/unitxt/dataset.py, src/unitxt/metric.py, src/unitxt/operators.py, src/unitxt/struct_data_operators.py, tests/library/test_recipe.py, tests/library/test_struct_data_operators.py
* Added new serialization operators for structured data: Table rows, Triples & KeyValue pairs
* Renamed table_operators -> struct_data_operators so that it best captures all structured data operators like the ones for Tables, Triples etc. and makes better sense to add other structured data operators to this in future.
* Added 3 new datatask cards to validate new operators
- wiki_bio : KeyValue Pair to Text(Data2Text task), Uses KeyValuePairs Serializer
- dart : Triples to Text(Data2Text task), Uses TriplesSerializer
- tablerow_classify : Table row classification using a Kaggle dataset(Heart disease prediction), Uses TableRowSerializer
=> structured data operators for serializing tablerows, triples and keyvalue pairs added

prepare/cards/ffqa_filtered.py, prepare/templates/qa/with_context.py, src/unitxt/catalog/cards/ffqa_filtered/16k.json, src/unitxt/catalog/cards/ffqa_filtered/2k.json, src/unitxt/catalog/cards/ffqa_filtered/4k.json, src/unitxt/catalog/cards/ffqa_filtered/8k.json, src/unitxt/catalog/templates/qa/with_context/all.json, src/unitxt/catalog/templates/qa/with_context/ffqa.json
Add [WikiQA-Free_Form_QA dataset](https://huggingface.co/datasets/abacusai/WikiQA-Free_Form_QA), a long context QA dataset.
This dataset is formatted to be used in chat format, but I want to experiment with 8k context LLM, so I implemented preprocess_steps accordingly.
=> Add filtered ffqa dataset

prepare/cards/cohere_for_ai.py, src/unitxt/catalog/cards/cohere_for_ai/aya_human_annotated/deu.json, src/unitxt/catalog/cards/cohere_for_ai/aya_human_annotated/eng.json, src/unitxt/catalog/cards/cohere_for_ai/aya_human_annotated/fra.json, src/unitxt/catalog/cards/cohere_for_ai/aya_human_annotated/jpn.json, src/unitxt/catalog/cards/cohere_for_ai/aya_human_annotated/por.json, src/unitxt/catalog/cards/cohere_for_ai/aya_human_annotated/spa.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_human_edited/fra.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_human_edited/spa.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_machine_translated/deu.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_machine_translated/eng.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_machine_translated/fra.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_machine_translated/jpn.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_machine_translated/por.json, src/unitxt/catalog/cards/cohere_for_ai/dolly_machine_translated/spa.json, src/unitxt/loaders.py, tests/library/test_loaders.py
per @elronbandel comment in [recent PR](https://github.com/IBM/unitxt/pull/579):  
Perhaps employing the HuggingFace filter upfront can ease load on the system, better than increase loading_limit only to allow the following pre-processing step that filters out.
=> filter on loading rather than increase loading limit

requirements/base.rqr
This is required for confidence intervals computation.
To resolve:
```
(unitxt_env) matanorbach@matans-mbp unitxt % unitxt-explore
Traceback (most recent call last):
File "/Users/matanorbach/opt/anaconda3/envs/unitxt_env/bin/unitxt-explore", line 5, in <module>
from unitxt.ui import launch
File "/Users/matanorbach/Documents/matan/src/fm_eval_workspace/metric_service/unitxt/src/unitxt/__init__.py", line 9, in <module>
register_all_artifacts()
File "/Users/matanorbach/Documents/matan/src/fm_eval_workspace/metric_service/unitxt/src/unitxt/register.py", line 106, in register_all_artifacts
ProjectArtifactRegisterer()
File "/Users/matanorbach/Documents/matan/src/fm_eval_workspace/metric_service/unitxt/src/unitxt/utils.py", line 12, in __call__
cls._instances[cls] = super().__call__(*args, …
```
=> Add scipy to base requirements

prepare/cards/ffqa_filtered.py, prepare/templates/qa/with_context.py, src/unitxt/catalog/cards/ffqa_filtered/16k.json, src/unitxt/catalog/cards/ffqa_filtered/2k.json, src/unitxt/catalog/cards/ffqa_filtered/4k.json, src/unitxt/catalog/cards/ffqa_filtered/8k.json, src/unitxt/catalog/templates/qa/with_context/ffqa.json
I was playing with the newly added ffqa cards.
I like the song  [these boots are made for walking](https://youtu.be/sbAM2HGGCVY), and was glad to see it among the first instances.. 
I suggest to shorten the text used for context. That text is so long, that printing it out generates "message too long" error on a linux console (I highlighted the error message):   
[ffqa_now_in_main.pdf](https://github.com/IBM/unitxt/files/14452506/ffqa_now_in_main.pdf)
I think that the  re.DOTALL flag used now misleads the regular expression engine, and it skips the \n\n looked for.
Last, and most importantly, the new features of Template allow to separate the instruction from the input, which comes handy in particular when using demos.
Here is how the printout looks when applying the above items, …
=> suggest new features of Tempate for ffqa

src/unitxt/artifact.py, src/unitxt/catalog.py, src/unitxt/eval_utils.py, src/unitxt/metrics.py, src/unitxt/utils.py, tests/library/test_artifact.py, tests/library/test_eval_utils.py, tests/library/test_recipe.py
This prevents any accidental changes to returned artifacts from affecting the cached objects.
Closes https://github.com/IBM/unitxt/issues/325
=> Return copies of artifacts from the artifacts cache

src/unitxt/metrics.py
Closes https://github.com/IBM/unitxt/issues/606
- For score based confidence interval computation, skip the computation if all instance-based scores have the same value (as suggested by @yoavkatz [here](https://github.com/IBM/unitxt/issues/482)).
- For global metric based confidence internal computation, filter out `RuntimeWarning` during the computation. This is for the case that the same metric value is computed over all resamplings. Since the metric computation per resampling is done in a callback used by scify's `bootsrtap` method, the computation cannot be simply aborted.
=> Avoid RuntimeWarning in confidence interval computation

prepare/metrics/accuracy.py, prepare/processors/processors.py, src/unitxt/catalog/metrics/accuracy_binary.json, src/unitxt/catalog/metrics/max_accuracy_binary.json, src/unitxt/catalog/processors/predictions_yes_1_else_0.json, src/unitxt/metrics.py, src/unitxt/processors.py, tests/library/test_metrics.py, tests/library/test_postprocessors.py
1. Calculate accuracy, f1, precision and recall using a threshold
2. Calculate max F1 and max accuracy
=> Add metrics for binary tasks with float predictions

src/unitxt/loaders.py
`os.path` does not allow `None`
=> fix: LoadFromIBMCloud empty data_dir breaks processing

prepare/metrics/unsorted_list_exact_match.py, src/unitxt/catalog/metrics/unsorted_list_exact_match.json, src/unitxt/metrics.py, tests/library/test_metrics.py
The new metrics sorts the predictions and references (which are both assumed to be list) and compares them return '1' if exact match or '0' otherwise.
=> Added new metric for unsorted_list_exact_math

src/unitxt/loaders.py, tests/library/test_loaders.py
Closes: https://github.com/IBM/unitxt/issues/695
=> Add pandas_load_args for LoadCSV

requirements/base.rqr, requirements/docs.rqr, src/unitxt/dict_utils.py, src/unitxt/operators.py, tests/library/test_dict_utils.py, tests/library/test_operators.py
Hi Elron and Yoav,
d_path is out of dict_utility, and of both requirement files where it showed.
I also cancelled the ban of  `process_every_value`  not allowed for operator `RemoveValues` (a ban laid only on it..)
We do need `process_every_value` here.
Speaking of which (the family of field operators, including all the postprocessors, that process a (single) prediction and `process every value` of list of references), why is `EncodeLabels`  so much of an outsider?  
There is a straightforward implementation thereof as a field operator. Why was not it used?
=> removal of dpath -- ready for review

src/unitxt/settings_utils.py, tests/library/test_settings.py
Currently when unitxt settings are set via environment variables, boolean parameters are processed as strings, and thus a value of "False" can be evaluated as True by unitxt. This change casts the relevant setting values to boolean
=> Fix handling of boolean environment variables

src/unitxt/fusion.py, src/unitxt/loaders.py, tests/library/test_fusion.py, tests/library/test_loaders.py
(e.g one with "train" split and one with "test" split)
=> Add ability to fuse sources with disjoint splits 

prepare/metrics/custom_f1.py, src/unitxt/metrics.py, tests/library/test_metrics.py
Sometimes there are many groups in customF1 and it's not interesting to see results for each.
This PR allows disabling the reporting of these score.
=> Allow disabling per group f1 scores in customF1

src/unitxt/metrics.py, tests/library/test_metrics.py
This PR is a simple addition to the `metrics` file in order to support incoming risk detectors. 
Detectors are small, typically BERT-like, classification models which take as input a sentence and output a probability score.
The current test file is a placeholder, using an [open source model](https://huggingface.co/MilaNLProc/bert-base-uncased-ear-misogyny) while we work through clearances for the detectors.
=> Adding Detector metric for running any classifier from huggingface as a metric

src/unitxt/collections_operators.py, src/unitxt/string_operators.py, tests/catalog/test_preparation.py, tests/library/test_collections_operators.py, tests/library/test_string_operators.py
Usage examples:
```python 
Chunk(field="x", size=2)
RegexSplit(field="text", by=r"([\s,!?]+)")
TokensSplit(field="text", model="bert-base-uncased")
```
All the examples above has input-output examples in the tests.
=> Add operators: RegexSplit, TokensSplit, Chunk

src/unitxt/metrics.py, tests/library/test_metrics.py
Currently:
```
metric = BinaryMaxAccuracy()
references = [["0"], ["0"], ["0"]]
predictions = ["0.3", "0.5", "0"]
outputs = apply_metric(
metric=metric, predictions=predictions, references=references
)
print(outputs[0]["score"]["global"])
```
prints out:
```
{'max_accuracy_binary': 0.6666666666666666, 'best_thr_max_acc': 0.5, 'score': 
0.6666666666666666, 'score_name': 'max_accuracy_binary', 'score_ci_low': nan, 
'score_ci_high': nan, 'max_accuracy_binary_ci_low': nan, 
'max_accuracy_binary_ci_high': nan}
```       
Although clearly accuracy = 1.0 can be obtained for any thr > 0.5.  E.g for thr = 0.7.
This PR fixes this small bug, and while the hood is open, suggests an  n log n algorithm to replace the n^2 existing one, for the fun of it.
=> fix a small bug in BinaryMaxAccuracy

src/unitxt/standard.py
Some Loaders to not respect LoaderLimit.
For this we added a StreamRefiner step that forces the limit.  
This step was removed in a refactor recently and is returned.
=> Return loading step to enforce loader limit.

src/unitxt/operators.py, tests/library/test_operators.py
Add a sub-class of Shuffle operator that, rather than shuffling all the instances individually, first groups instances within a page by desired grouping features, then shuffles the groups as a block.  This is necessary for our robustness metric work, where we want a test dataset to contain complete-blocks of question paraphrases (the groups).
=> Group shuffle

src/unitxt/ui/load_catalog_data.py
Failure was due to a wrong variable being checked.
python ./fm_eval/utils/run_ui.py
File "/Users/XXXXl/PycharmProjects/unitxt/src/unitxt/ui/load_catalog_data.py", line 34, in get_from_str
if template_data.endswith(".all"):
AttributeError: 'list' object has no attribute 'endswith'
=> Fix UI load failure due to typo

src/unitxt/standard.py
Today, we added the createDemosPool operator even when num_demos is 0, this caused problems in debug=True in test card, because the demo stream was fetched (and could not be accessed because if no train set existed)
=> Avoid creating a demo pool if num_demos is 0.

docs/docs/helm.rst
The latest HELM release has the Unitxt integration included, so we can now install from PyPI instead of GitHub.
=> Update instructions to install HELM from PyPI

src/unitxt/standard.py
Reverts IBM/unitxt#787
Reason is that if demos_taken_from=test, and demo_pool_size=100, we don't want the test set to change if num_demo > 0 (removing the demos from test set) and be different when num_demos =0 (not removing demos from test set).
=> Revert "Avoid creating a demo pool if num_demos is 0."

src/unitxt/metrics.py
When using unitxt to evaluate with multiprocessing and the file system is shared between the processes, `evaluate.load()` can throw multiple errors, or it can be loaded successfully but fail to execute. Setting a unique experiment_id prevents this behavior.
Signed-off-by: ALON HALFON <ALONHAL@il.ibm.com>
=> Fix missing experiment_id for multiprocessing evaluation

src/unitxt/task.py
=> Add cache to metric prediction_type to speedup

src/unitxt/fusion.py, src/unitxt/loaders.py, src/unitxt/metric_utils.py, src/unitxt/operators.py, tests/library/test_fusion.py, tests/library/test_loaders.py, tests/library/test_metric_utils.py, tests/library/test_metrics.py
of each instance 
per issue #764
=> fuse, split, MultiStreamScoreMean, and merge all

prepare/cards/legalbench.py, prepare/tasks/classification.py, src/unitxt/catalog/cards/legalbench/abercrombie.json, src/unitxt/catalog/cards/legalbench/corporate_lobbying.json, src/unitxt/catalog/cards/legalbench/function_of_decision_section.json, src/unitxt/catalog/cards/legalbench/international_citizenship_questions.json, src/unitxt/catalog/cards/legalbench/proa.json, src/unitxt/catalog/tasks/classification/multi_class/with_classes_descriptions.json, src/unitxt/string_operators.py
The LegalBench project is an ongoing open science effort to collaboratively curate tasks for evaluating legal reasoning in English large language models (LLMs). The benchmark currently consists of 162 tasks gathered from 40 contributors.
https://github.com/HazyResearch/legalbench/tree/main
Here, although adding only the 5 tasks appearing in HELM, we are also laying the foundations for adding many more of them.
=> Add 5 legalbench tasks (the 5 existing in HELM)

prepare/cards/cohere_for_ai.py, prepare/cards/financebench.py, src/unitxt/catalog/cards/financebench.json
FinanceBench is a fsuite for evaluating the performance of LLMs on open book financial question answering (QA). It is an open source sample of 150 annotated examples used in the evaluation and analysis of models assessed in the FinanceBench paper.
https://huggingface.co/datasets/PatronusAI/financebench?row=0
Currently the dataset is implemented as a contextual qa with the evidence as contexts, this is the _Oracle_ scenario in the paper (https://arxiv.org/abs/2311.11944)
Will add more tasks if I see a reason (saturation for example).
=> Add financebench

prepare/cards/tldr.py, src/unitxt/catalog/cards/tldr.json
The corpus contains preprocessed posts from the Reddit dataset (Webis-TLDR-17). The dataset consists of 3,848,330 posts with an average length of 270 words for content, and 28 words for the summary.
https://huggingface.co/datasets/webis/tldr-17
https://aclanthology.org/W17-4508/
In the scope of the task of absractive summarization the creators of the Webis-TLDR-17 propose mining social media for author-provided summaries and taking advantage of the common practice of appending a "TL;DR" to long posts. A large Reddit crawl was used to yield the Webis-TLDR-17 corpus. This dataset intends to complement the existing summarization corpora primarily from the news genre.
=> Add tldr dataset

src/unitxt/metrics.py, tests/library/test_metrics.py
The new feature of Metric, sample-from-groups-scores, employs the CI over instances generated ad-hoc, one per group (a group is a subset of the input instances, whose member instances are those instances of the stream having a specific value in a specific field).  CI generates the samples through first generating a list of indices (into the input instances) and then dealing with the instances thus indexed. 
Hence, the result of CI for these instances generated ad-hoc depends on the order in which these instances are fed into CI.
This PR standardizes this order by the alphabetic order of the values that define the groups (as explained above)
=> Ensure consistent evaluation of CI across implementations [Might change previous results]

src/unitxt/blocks.py, src/unitxt/task.py
1. Docs were not all changed
2. It was not imported in unitxt.blocks so many cards continued to fail
=> FormTask deprecation

src/unitxt/loaders.py, tests/library/test_loaders.py
Added a possibility to load data from Huggingface spaces as per #857
=> Added loader from HF spaces

src/unitxt/operator.py, src/unitxt/standard.py, src/unitxt/test_utils/card.py, src/unitxt/text_utils.py
Right now testing of card using test_card performs  multiple checks implicitly (e.g generate the card with number of demos).
The goal of this pull request is to make things more explict, and more controllable by the users.
1. Do not add any defaults beyond what the user provide (e.g num demos) 
2. Improved debug messages.
3. Allow user to override the values when testing the card on random predictions.
=> Improved testing of cards

prepare/operators/balancers/per_task.py, src/unitxt/catalog/operators/balancers/classification/minimum_one_example_per_class.json, src/unitxt/operators.py, tests/library/test_operators.py
to allow having at least one element per label when using a sub-sample of the train set
unit tests to show the expected behavior.
Signed-off-by: ALON HALFON <ALONHAL@il.ibm.com>
=> add MinimumOneExamplePerLabelRefiner

src/unitxt/dict_utils.py, src/unitxt/metrics.py, src/unitxt/operators.py, src/unitxt/standard.py, src/unitxt/test_utils/card.py, tests/library/test_metrics.py, tests/library/test_operators.py
here were some very subtle bugs in treatment of operators.
The issue was that if we assign a field to a field (E.g in CopyField operator) , and these are both fields that are dictionary.
then field the dictionary values of the source field were copied to the target field.
If the one of these fields, was further modified - they effected on another.
CopyField(pred -> pred_orig)
CopyField(pred/contexts -> refs)
ListFields[task/question -> pred)
Following this, pred_orig was equal to the task/question.
As a first solution - I a deep copied instances in instance operators, so they don't effect each other.
Another issue was that metric global scores were shared across instances, and this also caused problems following the above change. The code was simplified that each global score is a …
=> Fix operator and metrics data bugs and add metric prefix in main

src/unitxt/loaders.py, tests/library/test_loaders.py
Added check that input of LoadFromDictorionary has a multiple splits, each with a list of instances with the same fields.
=> Add input type checking in LoadFromDictionary

src/unitxt/loaders.py
FIX: `renames` instead of `rename` to account for slashes in data_file
If the destination path includes directories that do not exist, ﻿os.renames will create those intermediate directories.
=> fix(cos loader): account for slashes in cos file name

examples/qa_evaluation.py, examples/standalone_qa_evaluation.py, src/unitxt/api.py, tests/library/test_api.py
`unitxt.api.load_dataset` now also supports loading cards which are not present in local catalog
For #924
=> load_dataset supports loading cards not present in local catalog

prepare/cards/safety/truthful_qa.py, src/unitxt/catalog/cards/safety/truthful_qa.json
Implementation of a card for the TruthfulQA dataset. Current support is limited to the multiple-choice version, with single correct answer.
=> Implementation of TruthfulQA

prepare/cards/safety/bbq.py, prepare/cards/safety/truthful_qa.py, prepare/templates/qa/multiple_choice/templates.py, src/unitxt/catalog/cards/safety/bbq/Age.json, src/unitxt/catalog/cards/safety/bbq/Disability_status.json, src/unitxt/catalog/cards/safety/bbq/Gender_identity.json, src/unitxt/catalog/cards/safety/bbq/Nationality.json, src/unitxt/catalog/cards/safety/bbq/Physical_appearance.json, src/unitxt/catalog/cards/safety/bbq/Race_ethnicity.json, src/unitxt/catalog/cards/safety/bbq/Race_x_SES.json, src/unitxt/catalog/cards/safety/bbq/Race_x_gender.json, src/unitxt/catalog/cards/safety/bbq/Religion.json, src/unitxt/catalog/cards/safety/bbq/SES.json, src/unitxt/catalog/cards/safety/bbq/Sexual_orientation.json, src/unitxt/catalog/cards/safety/truthful_qa.json, src/unitxt/catalog/templates/qa/multiple_choice/helm.json
Added additional applicable templates to the BBQ and TruthfulQA cards.
TruthfulQA now matches the HELM implementation.
=> Expanded template support for safety cards

prepare/metrics/llm_as_judge/rating/llama_3_ibm_genai_generic_template.py, src/unitxt/catalog/metrics/llm_as_judge/rating/llama_3_70b_instruct_ibm_genai_template_generic_single_turn.json
This [example](https://github.com/IBM/unitxt/blob/main/examples/evaluate_dataset_by_llm_as_judge_no_install.py) is failing for me because the metric can not find the `llama3_chat` format.
According to [this discussion](https://github.com/IBM/unitxt/pull/950#discussion_r1657537711) the `llama3_chat` and `llama3_instruct` formats are the same.
I changed the format and the example works for me now.
=> Fix llama_3_ibm_genai_generic_template

src/unitxt/formats.py, tests/library/test_formats.py
Formats the complete input for the model using the Hugginface chat template of a given model.
HFSystemFormat expects the input instance to contain:
1. A field named "system_prompt" whose value is a string (potentially empty) that delivers a task independent opening text.
2. A field named "source" whose value is a string verbalizing the original values in the instance (as read
from the source dataset), in the context of the underlying task.
3. A field named "instruction" that contains a (non-None) string.
4. A field named with the value in arg 'demos_field', containing a list of dicts, each dict with fields "source"
and "target", representing a single demo.
5. A field named "target_prefx" that contains a string to prefix the target in both each demo, and to end the whole generated prompt …
=> Added a format based on Huggingface format

src/unitxt/inference.py
Provided backward compatibility for inference engines (support for passing inference parameters as a class to an engine)
For #1019
=> Backward compatibility for inference engines

prepare/tasks/rag/response_generation.py, src/unitxt/catalog/tasks/rag/response_generation.json
some RAG datasets has a hash instead of an int context id
=> Add string to context id in rag

prepare/metrics/code_mixing_detection.py, src/unitxt/test_utils/metrics.py
There were two problems that prevented running 
python utils/prepare_all_artifacts.py
on fresh installs.
evaluate_metric - should not be run if test_metric_disable is True (because prepare/verify method are not called).
This is simulate to test_metric.
Code_mixing_detection.py should not require torch in imports.
=> Fixed issues with fresh install

.secrets.baseline, prepare/metrics/meteor.py, prepare/metrics/rouge.py, src/unitxt/catalog/metrics/meteor.json, src/unitxt/catalog/metrics/meteor_with_confidence_intervals.json, src/unitxt/catalog/metrics/rouge.json, src/unitxt/catalog/metrics/rouge_with_confidence_intervals.json, src/unitxt/metrics.py, src/unitxt/standard.py, tests/library/test_metric_utils.py, tests/library/test_metrics.py
added a new metric with interval calculations
=> Refactor Rouge and Meteor to InstanceMetric for faster score computation

src/unitxt/splitters.py, src/unitxt/standard.py, tests/library/test_api.py, tests/library/test_recipe.py, tests/library/test_splitters.py
CloseTextSampler -  returns demos that are textually close to the current instance.
FixedIndicesSampler - return fixed demos based on indices in the train pool
Also fixed a bug in reproducibility of demos by making sure randomization is based on instance, and being global (so it is shared with ther instances)
=> Add CloseTextSampler and FixedIndicesSampler

docs/docs/adding_template.rst, src/unitxt/llm_as_judge.py, src/unitxt/task.py, src/unitxt/templates.py, tests/library/test_format_and_template_interaction.py, tests/library/test_formats.py, tests/library/test_metrics.py, tests/library/test_operators.py, tests/library/test_templates.py
This is to continues  the work done on tasks.
Non backward compatible
Template methods changes:
```
inputs_to_instruction_and_target_prefix(self, inputs) ->    input_fields_to_instruction_and_target_prefix(self, input_fields)
inputs_to_source(self, inputs: Dict[str, object]) ->  input_fields_to_source(self, input_fields: Dict[str, object])
outputs_to_target_and_references(self, outputs: Dict[str, object]) -> reference_fields_to_target_and_references(self, reference_fields: Dict[str, object])
preprocess_inputs_and_outputs(   self, inputs: Dict[str, Any], outputs: Dict[str, Any] --> preprocess_input_and_reference_fields(self, input_fields: Dict[str, Any], reference_fields: Dict[str, Any]
```
=> changed input and output of templates to "input_fields" and "reference_ fields" - Non backward compatible

src/unitxt/hf_utils.py, src/unitxt/operator.py, src/unitxt/utils.py
This is so minimal requirement installation will still work.
Also changed to missing requirements will be reported before the requirements are used.
=> Remove import pkg_resources from utils

examples/evaluate_different_formats.py, prepare/formats/models/deepseek_coder.py, prepare/system_prompts/models/deepseek_coder.py, src/unitxt/catalog/formats/deepseek_coder.json, src/unitxt/catalog/system_prompts/models/deepseek_coder.json
Adding a format and a system prompt for DeepSeek-Coder family of models (v1) based on the prompt template shown here: https://github.com/deepseek-ai/deepseek-coder
I couldn't find any existing format that was the same or similar. I've tested these on two tasks, and they seem to work well and improve the results compared with no format or system prompt.
=> DeepSeek-Coder format and system prompt

src/unitxt/inference.py
Several minor changes to `WMLInferenceEngine`:
* removed support for passing instances of both `ibm_watsonx_ai.client.APIClient` and `ibm_watsonx_ai.credentials.Credentials` as they are not JSON-serializable 
* if given, `credentials` should be now only of type `dict[str, str]`
* overwritten `to_json` method which now hides credentials (in case they were directly given by a user); when `credentials` are read from env, they're not visible in JSON
* modified the `_infer` method to make use of concurrency in `generate_text` method
=> Fixes to WMLInferenceEngine

tests/library/test_metrics.py
- text_context_correctness -> test_context_correctness
- Fix the context_correctness metric names in the test, so it passes
Closes https://github.com/IBM/unitxt/issues/1136
=> Fix typo in method name, and the contained test

docs/docs/debugging.rst
word order on a flag, adverb vs adjective (fully mismatched vs full mismatched), typo artifict to artifact
=> Update debugging.rst -- more minor copy changes to documentation

src/unitxt/operators.py
In addition to fixing typos for the word "specialized" and changed "dedicated for" to "dedicated to" -- I also adjusted something that seemed to render differently than planned --
The auto docs said
"additional arguments are field names passed to the function" 
but it showed up on the web page as
"(additional arguments are field names passed to the) - name of function" 
-- it seemed to render this way since the word "function" was at the end.
Incorporating Yoav's new suggested text for clarity, I also switched the final words so that it didn't end with the word function, which seemed to be picked up there by the parser.
I hope this renders better. We can check by looking at the operators.html page on the resulting documentation website after this commit is approved, and if it doesn't work …
=> Update operators.py --- copy edits (grammar, consistency, clarity) - take 2

.secrets.baseline, src/unitxt/dataclass.py, src/unitxt/metrics.py, src/unitxt/operators.py, src/unitxt/task.py
Currently in branch `main`, the last `assert` in` test_operators.test_rename`  passes also when `, use_query=True` is removed.
=> make deprecated field print warning message for the right reason

docs/docs/installation.rst
The variable `scores` was used without definition. The variable `dataset_with_scores` should be used instead.
=> Docfix: Fix typo in Installation doc

src/unitxt/loaders.py
Nested JSON dataset is a scenario where multiple datasets are written in a single JSON file, e.g.
```
{
"dataset1": [
{
"question": "q1",
"answer": "B",
"choices": ["A", "B", "C", "D"],
},
{
"question": "q2",
"answer": "D",
"choices": ["A", "B", "C", "D"],
}
],
"dataset2": [
{
"question": "q1",
"answer": "B",
"choices": ["A", "B", "C", "D"],
},
{
"question": "q2",
"answer": "C",
"choices": ["A", "B", "C", "D"],
}
]
}
```
HF datasets supports loading datasets in such scenario by using the `field` arg in the loading method, see example in: https://huggingface.co/docs/datasets/v1.11.0/loading_datasets.html#json-files
The `field` argument propagates to the `JsonConfig` data class.
This PR adds the ability to load nested JSON datasets when using the `load_from_ibm_cloud` loader, by adding …
=> Support dataset field in nested JSON files

prepare/cards/turl_col_type.py, src/unitxt/catalog/cards/turl_col_type.json
Adds a new task card for table column type annotation task using TURL dataset. The dataset is loaded via a custom dataset loading script hosted in [HF Datasets repo](https://huggingface.co/datasets/ibm/turl_table_col_type).
=> Add TURL Table column type annotation task card

src/unitxt/llm_as_judge.py
Currently, `OpenAiInferenceEngine` cannot be used for `LLMAsJudge` because `self.format` and `self.system_prompt` are never `None`, so we always get `ValueError: Error in 'LLMAsJudge' metric. Inference model 'OpenAiInferenceEngine' does not support formatting. Please remove the format definition from the recipe (OpenAi Chat API take care of the formatting automatically).`
Instead, check if `self.format` and `self.system_prompt` are the default values.
=> Fix using OpenAiInferenceEngine for LLMAsJudge

prepare/metrics/rag_context_correctness.py, tests/library/test_metrics.py
from test_metrics.py to rag_context_correctness.py
This is following the discussion here: https://github.com/IBM/unitxt/pull/1131#issuecomment-2290889580, that `checking catalog assets should be done at the prepare file when the catalog assets are added`.
=> Move test_context_correctness

examples/run_generic_inference_engine.py, prepare/engines/ibm_genai/llama3.py, prepare/engines/ollama/llama2.py, src/unitxt/catalog/engine/generic.json, src/unitxt/catalog/engines/ibm_gen_ai/llama_3_70b_instruct.json, src/unitxt/catalog/engines/ibm_gen_ai/llama_3_8b_instruct.json, src/unitxt/catalog/engines/ollama/llama2.json, src/unitxt/inference.py
The generic inference engine enables users to set the actual inference engine dynamically via the inference_engine environment variable. Additionally, the class includes a default parameter, which specifies the inference engine to use if the environment variable is not set.
For example, when the inference_engine variable is not set, the engine will
default to ibm_gen_ai.llama_3_8b_instruct. However, if
inference_engine=ollama.llama2 is set, it will switch to the Ollama model.
This update allows lm-eval users to run the UniTXT dataset with LLMaaJ using any supported inference engine.
=> Add generic inference engine to allow dynamic selection by the user

src/unitxt/inference.py
Closes: https://github.com/IBM/unitxt/issues/1215
=> Add concurency_limit parameter to WMLInferenceEngine

src/unitxt/struct_data_operators.py
If column appear twice it just delete it, now it will give it a suffix _1, _2 etc
=> Fix duplicate column deletion bug in pandas serializer

prepare/cards/scigen.py, src/unitxt/catalog/cards/scigen.json
There was an issue with post-processor for Scigen. Previously used template "templates.generation.from_pair.all" had a post-processor "processors.take_first_non_empty_line" which was ignoring all but first line from the generated text. This is not intended behaviour. Hence modified the template input in task-card to override post-processor from task-card itself.
=> fixed scigen post-processor

src/unitxt/dialog_operators.py
Right now the only "user" and "assistant" roles are allowed.  We want to make it case insensitive for it to be flexible in input format.
=> Allow role names to be captialized in SerializeOpenAiFormatDialog

.gitignore, CONTRIBUTING.md
The [CONTRIBUTING.md](https://github.com/IBM/unitxt/blob/main/CONTRIBUTING.md) tells us to create `unitxt-venv` but it's not included in `.gitignore`.
I also removed a typo.
=> Ignore unitxt-venv

src/unitxt/operators.py, tests/library/test_operators.py
If the value we map to is a list, we must deepcopy the value, otherwise external  changes to the list effect the value of the mapper .
=> Fix missing deep copy in MapInstanceValues

src/unitxt/formats.py
In this PR, I'm introducing the ability to add instructions to the demo section in SystemFormat class. 
This can sometimes be useful when working with prompts that follow the multi-turn convention:
```
<|start_of_role|>user<|end_of_role|>{{Instruction}}
{{ICL_Q1}}
<|end_of_text|>
<|start_of_role|>assistant<|end_of_role|>{{ICL_A1}}
<|end_of_text|>
<|start_of_role|>user<|end_of_role|>{{Instruction}}
{{ICL_Q2}}
<|end_of_text|>
<|start_of_role|>assistant<|end_of_role|>{{ICL_A2}}
<|end_of_text|>
<|start_of_role|>user<|end_of_role|>{{Instruction}}
{{ICL_Q3}}
<|end_of_text|>
<|start_of_role|>assistant<|end_of_role|>{{ICL_A3}}
<|end_of_text|>
<|start_of_role|>assistant<|end_of_role|>
```
especially when using templates that separate instructions from the input format.
=> Instruction in SystemFormet demo support.

.github/workflows/inference_tests.yml, src/unitxt/inference.py, tests/inference/test_inference_engine.py
- Add `OptionSelectingByLogProbsInferenceEngine`, an inference engine that is used to select an option based on the logprobs of an options list conditioned by a prompt.
- Implement `OptionSelectingByLogProbsInferenceEngine` in `WMLInferenceEngine` and `IbmGenAiInferenceEngine` inference engines.
- Add a test under `inference.test_inference_engine.TestInferenceEngine.test_option_selecting_by_log_prob_inference_engines`.
Command to run the test:
```bash
export GENAI_KEY="" && WML_PROJECT_ID="" && export WML_APIKEY="" && export WML_URL="https://us-south.ml.cloud.ibm.com" && python -m unittest tests.inference.test_inference_engine.TestInferenceEngine.test_option_selecting_by_log_prob_inference_engines
```
This inference engine is intended to be used to integrate …
=> Add OptionSelectingByLogProbsInferenceEngine

src/unitxt/llm_as_judge.py, tests/library/test_metrics.py
when using multiple llmaj metric, the raw input and output fields get overwritten because they have the same score name. This pr add score name prefix for judge_raw_output/input in llmaj metric
=> add score name prefix for judge_raw_output/input in llmaj metric

docs/blog/vision_robustness.rst, docs/docs/adding_dataset.rst, docs/docs/adding_metric.rst, docs/docs/adding_operator.rst, docs/docs/adding_template.rst, docs/docs/data_classification_policy.rst, docs/docs/examples.rst, docs/docs/glossary.rst, docs/docs/helm.rst, docs/docs/operators.rst, docs/docs/rag_support.rst, docs/docs/tutorials.rst, src/unitxt/augmentors.py, src/unitxt/loaders.py, src/unitxt/standard.py, src/unitxt/text_utils.py
Fixed many broken links. E.g.:
Before:
After:
linking to [this page](https://www.unitxt.ai/en/latest/catalog/catalog.__dir__.html)
=> Typos in the rst files

prepare/engines/cross_provider/llama3.py, prepare/engines/openai/gpt4o.py, prepare/engines/rits/llama3.py, src/unitxt/catalog/engines/cross_provider/llama_3_70b_instruct.json, src/unitxt/catalog/engines/cross_provider/llama_3_8b_instruct.json, src/unitxt/catalog/engines/openai/gpt_4o.json, src/unitxt/catalog/engines/rits/llama_3/1_8b_instruct.json, src/unitxt/catalog/engines/rits/llama_3_1_405b_instruct_fp8.json, src/unitxt/catalog/engines/rits/llama_3_1_70b_instruct.json
This PR adds RITS, OpenAI and CrossProvider examples to the catalog to the previously existing ones BAM and Watsonx.
=> Add inference engines to the catalog

src/unitxt/operator.py, src/unitxt/operators.py, src/unitxt/test_utils/operators.py, tests/library/test_augmentors.py, tests/library/test_operators.py, tests/library/test_templates.py
Up to now, exceptions texts were concatinated to create long (unreadble) error message.  This change makes sure each level adds only new information and refers to the causing exceptio
=> Reduce error message clutter

prepare/recipes/bluebench.py, src/unitxt/catalog/recipes/bluebench/chatbot_abilities/arena_hard_generation_english_gpt_4_0314_reference.json
LLMaJ metrics has an issue with the templates.empty, switching to templates.generation.empty
=> Fix arenahard bluebench template

prepare/metrics/hhem.py, prepare/metrics/rag.py, prepare/metrics/rag_answer_correctness.py, prepare/metrics/rag_context_relevance.py, prepare/metrics/rag_faithfulness.py, src/unitxt/catalog/metrics/rag/answer_correctness/sentence_bert_bge.json, src/unitxt/catalog/metrics/rag/answer_correctness/sentence_bert_mini_lm.json, src/unitxt/catalog/metrics/rag/context_relevance/sentence_bert_bge.json, src/unitxt/catalog/metrics/rag/context_relevance/sentence_bert_mini_lm.json, src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert_bge.json, src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert_mini_lm.json, src/unitxt/catalog/metrics/rag/faithfulness/vectara_hhem_2_1.json, src/unitxt/metrics.py
Using "score" as main_score disables scores_prefix (as prefix is not added to "score") and makes it impossible to track scores from a list of metric.
With this fix, the new main_score (and main_score_ci_) are added to the results, without changing the previous reported scores.
Signed-off-by: lilacheden <lilach.edel@gmail.com>
=> not using "score" as metric main_score

src/unitxt/artifact.py, src/unitxt/dataclass.py, tests/library/test_artifact.py
When assigning artifact dict in the constructor of another artifact unitxt should recover it but it wont. 
See unittests that did not pass before.
=> Fix artifact dict assignment bug

src/unitxt/api.py, src/unitxt/artifact.py, src/unitxt/dataclass.py, src/unitxt/dataset.py, src/unitxt/splitters.py, src/unitxt/test_utils/card.py
face lift to the documentation on the web pages for:
https://www.unitxt.ai/en/latest/unitxt.api.html#unitxt.api.load_dataset
https://www.unitxt.ai/en/latest/unitxt.artifact.html#unitxt.artifact.Artifact.verify_instance
https://www.unitxt.ai/en/latest/unitxt.splitters.html#unitxt.splitters.DiverseLabelsSampler
https://www.unitxt.ai/en/latest/unitxt.dataclass.html#unitxt.dataclass.Dataclass
https://www.unitxt.ai/en/latest/unitxt.dataset.html#unitxt.dataset.Dataset.as_dataset
https://www.unitxt.ai/en/latest/unitxt.test_utils.card.html#unitxt.test_utils.card.test_card
=> Indentation within docstrings to improve appearance on web pages, on the way - eliminating two red lines from "make docs-server"

docs/docs/adding_task.rst
Correct the function name in the task registration example.
=> Fix documentation for task registration example

examples/evaluate_external_rag_results_with_binary_llm_as_judge.py
a commit left out of the previous pr by mistake
=> fix external_rag example

docs/docs/llm_as_judge.rst, examples/evaluate_llm_as_judge_direct_predefined_criteria.py, examples/evaluate_llm_as_judge_direct_user_criteria_no_catalog.py
…Updated criterion in examples to be more practical
=> Updated documentation and examples of LLM-as-Judge

src/unitxt/assistant/app.py
The litellm.embaded used to faild since it handles the createion of authentication token using apikey, but it doesn't hadle the token time expiering. By reinit the package, litellm will create new token.
=> Solve issue of expired token in Unitxt Assistant

prepare/cards/wikitq.py, src/unitxt/catalog/cards/wikitq.json, src/unitxt/struct_data_operators.py
there are a few large tables, that cannot be added to the prompts (context window)
=> add a filter to wikitq

src/unitxt/inference.py
WML inference is expected to support either 'WML_SPACE_ID' or 'WML_PROJECT_ID' specified, however currently the code does not handle the case where only space id is specified.
=> fix: minor bug when only space id is provided for WML inference

docs/catalog.py, src/unitxt/inference.py, src/unitxt/llm_as_judge_from_template.py, src/unitxt/text_utils.py
E.g.:
and fixed two docstrings against red lines in `make docs-server`
=> present catalog entries as pieces of python code

src/unitxt/metrics.py, tests/library/test_metrics.py
This fixes a minor bug - the SQL executor can wrap the results in a dictionary inside a 'results' field, and we were comparing the output and gold DataFrames, including the 'results' field. As a result, column names were not ignored. I also revised the logic for comparing DataFrames.
=> Minor bug fix affecting Text2SQL execution accuracy

docs/_static/custom.css, docs/catalog.py
=> add 'show more' button for imports from unitxt modules

src/unitxt/inference.py
This PR adds more models to the Cross inference engine. In particular, it adds a complete list of models offered by watsonx. 
It does a refactor were `watsonx` models are a function of `watsonx-sdk` models, to avoid hardcoding those values.
=> CrossInferenceProvider: add more models

src/unitxt/loaders.py
When calling the LoadHF.load_dataset() with disable_memory_caching=True, the returning dataset is incorrect. Update the return value to fix the incorrect behavior.
=> Fix LoadHF.load_dataset() when mem-caching is off

src/unitxt/inference.py
Peft models don't have config.json, and therefore AutoConfig.from_pretrained may fail.
=> Support HFPipelineBasedInferenceEngine with PEFT model

src/unitxt/inference.py
closes: https://github.com/IBM/unitxt/issues/1699
=> Add unitxt version to inference cache keys

.github/workflows/stale_issues.yml
For better tracking of new issues, to increase responsiveness.
=> Mark issues stale after 30 days of no interaction. Closed them 15 days later.

docs/docs/cli.rst, docs/docs/tutorials.rst, docs/use_cases/special_tools.rst, src/unitxt/operators.py
=> Remove more red lines from make docs-server, and rehab lost sons 

src/unitxt/inference.py
Added support for the `instance_id` in WML credentials as it may be required in certain cases
=> Add instance ID to WML credentials

src/unitxt/inference.py
- Fix type in `azure_openai_host` variable name & credential dictionary key.
=> fix typo in azure_openai_host variable name

docs/docs/tool_calling.rst, docs/docs/tutorials.rst, examples/evaluate_tool_calling.py, prepare/cards/bfcl.py, prepare/metrics/tool_calling.py, prepare/processors/tool_calling.py, prepare/tasks/tool_calling/tasks.py, prepare/templates/tool_calling/templates.py, pyproject.toml, src/unitxt/catalog/cards/bfcl/simple_v3.json, src/unitxt/catalog/metrics/tool_calling.json, src/unitxt/catalog/processors/load_json_or_empty_tool_call.json, src/unitxt/catalog/tasks/tool_calling/supervised.json, src/unitxt/catalog/templates/tool_calling/base.json, src/unitxt/collections_operators.py, src/unitxt/dataset.py, src/unitxt/inference.py, src/unitxt/metric.py, src/unitxt/metrics.py, src/unitxt/operators.py, src/unitxt/schema.py, src/unitxt/serializers.py, src/unitxt/templates.py, src/unitxt/tool_calling.py, src/unitxt/type_utils.py, src/unitxt/types.py, tests/library/test_metrics.py, tests/library/test_tool_calling.py, tests/library/test_type_utils.py
`python examples/evaluate_tool_calling.py`
```
Inferring batch 4 / 5 with 100 instances (found 0 instances in ./inference_engine_cache/CrossProviderInferenceEngine)
LiteLLM Inference (watsonx/ibm/granite-3-3-8b-instruct): 100%|█████████████████| 100/100 [00:17<00:00,  5.71it/s]
Global Results:
| score_name       |   score |   ci_low |   ci_high |
|:-----------------|--------:|---------:|----------:|
| exact_match      |    0    |     0    |      0    |
| parameter_choice |    1    |     1    |      1    |
| parameter_values |    0.83 |     0.8  |      0.85 |
| parameters_types |    1    |     0.99 |      1    |
| score            |    0    |     0    |      0    |
| tool_choice      |    0.98 |     0.96 |      0.99 |
```
=> Add tool calling support + Berekley Tool Calling Benchmark (simple-v3)

prepare/cards/arena_hard/generation/english_gpt-4-0314_reference.py, src/unitxt/catalog/cards/arena_hard/generation/english_gpt_4_0314_reference.json
`'lmsys/arena-hard-browser'` was gone from HF.  `test_preparation` does not catch faulty `prepare/cards/arena_hard/generation/english_gpt-4-0314_reference.py` that tries to access this (gone) dataset, because a missing dataset is considered by `test_preparation`  an error to be ignored.   Performance, however, failed on it. 
So here a potentially good enough dataset is used instead:     
https://github.com/lmarena/arena-hard-auto  that is pointed at from https://paperswithcode.com/dataset/arena-hard
=> trying to fix PERFORMANCE:  use a github repository as a replacement for the gone HF 'lmsys/arena-hard-browser'

src/unitxt/artifact.py
This is required to allow exporting a python representation of the artficat to systems that expect yaml input.
=> Added to_yaml shorthand function to artifact

.github/workflows/catalog_preparation.yml
comparing to https://github.com/IBM/unitxt/pull/1782 , for example, [and its commit to main](https://github.com/IBM/unitxt/commit/4093178b6c2282b95f676887b5cab1e2e75f0826) .
[Example for the error raised in datasets=3.6.0.](https://github.com/IBM/unitxt/actions/runs/14921477764/job/41917525279)
=> Reverting to datasets=351 can solve problems in test catalog preparation

.github/workflows/examples_tests.yml, .github/workflows/performance.yml, performance/bluebench_profiler.py, performance/compare_benchmark_performance_results.py
`bluebench_profiler` now reports times based on time() diffs, rather than accumulating over reports of cProfile, over methods whose names seem to be relevant.   Still, a full cProfile report (nicely viewable by snakeviz) is generated with the flag `--employ_cProfile`
=> Performance to report accurate times based on end-to-end time() diffs, rather than accumulate cProfile numbers over methods whose names seem relevant

prepare/engines/classification/classification_engines.py, prepare/metrics/llm_as_judge/rag_judge.py, src/unitxt/catalog/engines/classification/mistral_small_3_1_24b_instruct_2503_wml.json, src/unitxt/catalog/metrics/rag/end_to_end/answer_correctness/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/end_to_end/answer_relevance/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/end_to_end/context_relevance/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/end_to_end/faithfulness/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/external_rag/answer_correctness/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/external_rag/answer_relevance/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/external_rag/context_relevance/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/external_rag/faithfulness/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/response_generation/answer_correctness/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/response_generation/answer_relevance/mistral_small_3_1_24b_instruct_2503_wml_judge.json, src/unitxt/catalog/metrics/rag/response_generation/faithfulness/mistral_small_3_1_24b_instruct_2503_wml_judge.json
LLMaJ with mistral-small from watsonx.ai (via ibm-watsonx-ai SDK).
=> watsonx.ai mistral small support

src/unitxt/inference.py
This PR corrects the following line:
```python
number_of_batches = len(dataset) // self.cache_batch_size + 1
```
If the result of the `//` calculation has no decimal part it is not required to add 1. For example if dataset len is 200 and batch_size is 100: 200 // 100 + 1 = 3 and not 2.
Correcte line:
```python
number_of_batches = math.ceil(len(dataset) / self.cache_batch_size)
```
=> Fix: number of batches calculation is incorrect

prepare/cards/judge_bench/inferential_strategies.py, src/unitxt/catalog/cards/judge_bench/inferential_strategies/sound_reasoning.json, src/unitxt/operators.py, tests/library/test_operators.py
Currently, Filter by condition throws an exception if a field participating in the condition is missing from the instance.
Suggesting here to extend conditions to also handle the very existence of the field in the instance as a measure of this instance being required.  
This can be handy for cleaning datasets in some of the cards, which now throw exception for a missing field (breaking the pre-processing pipeline), and also, indirectly, shed light on cards that are totally erroneous, and are better be removed from the catalog:
E.g. for helpful cleaning:
Currently:
whereas [pushing the new operators in the card](https://github.com/IBM/unitxt/pull/1879/files#diff-c0511cc100f69c845f48afdd069a0e19f4c08138fd4e0cb81a8d35adefbc5ca5), yields:
Another example, that makes us consider a removal of a …
=> extend condition to also filter by field exists or not

performance/bluebench_profiler.py, performance/compare_benchmark_performance_results.py
through removal from performance evaluation of `_source_to_dataset`, which generated a 403 to the dataset of recipe `cfpb_product_2023`, although the access to this dataset is free no problem:
=> fix performance test 

prepare/cards/xlam_function_calling.py, src/unitxt/catalog/cards/xlam_function_calling_60k.json, src/unitxt/operators.py
cars `cards.xlam_function_calling_60k` exhibits schema issues: when the recipe generated therefrom is fed to `_source_to_dataset`, schema issues pop up:
[xlam_main.pdf](https://github.com/user-attachments/files/21756661/xlam_main.pdf)
the error shown above is the value "int, optional"  for a type field in a tool, but down the dataset there are more involved types. e.g.:
So introduced here is a more elaborated operator to fix for json-schema adherence.
This PR alsp fixes the order of pre-process steps, in order to not skip any tool.
End result:
=> fix xlam's schema issues

prepare/cards/safety/airbench2024.py, src/unitxt/catalog/cards/safety/airbench2024.json
**BEFORE:**
[safety_airbench2024_main.pdf](https://github.com/user-attachments/files/21957492/safety_airbench2024_main.pdf)
**AFTER:**
[safety_airbench2024_fixed.pdf](https://github.com/user-attachments/files/21957500/safety_airbench2024_fixed.pdf)
=> remove redundant split from airbench2024

prepare/cards/biggen_bench.py, prepare/cards/judge_bench/newsroom.py, prepare/cards/judge_bench/roscoe_overall.py, prepare/cards/judge_bench/wmt-human.py, src/unitxt/catalog/cards/biggen_bench/results/human_eval.json, src/unitxt/catalog/cards/judge_bench/newswoom/coherence.json, src/unitxt/catalog/cards/judge_bench/newswoom/fluency.json, src/unitxt/catalog/cards/judge_bench/newswoom/informativeness.json, src/unitxt/catalog/cards/judge_bench/newswoom/relevance.json, src/unitxt/catalog/cards/judge_bench/roscoe/overall/cosmos/coherence.json, src/unitxt/catalog/cards/judge_bench/roscoe/overall/cosmos/overall_quality.json, src/unitxt/catalog/cards/judge_bench/roscoe/overall/drop/coherence.json, src/unitxt/catalog/cards/judge_bench/roscoe/overall/drop/overall_quality.json, src/unitxt/catalog/cards/judge_bench/roscoe/overall/esnli/coherence.json, src/unitxt/catalog/cards/judge_bench/roscoe/overall/esnli/overall_quality.json, src/unitxt/catalog/cards/judge_bench/wmt_human/chinese_to_english/quality.json, src/unitxt/catalog/cards/judge_bench/wmt_human/english_to_german/quality.json
This PR normalizes the target variable (ground truth) of the judgebench and biggen cards, where applicable. They are linearly normalized using the function: `normalize(x) = (x - min(x)) / (max(x) - min(x))`. So, a Likert scale (1-5) is mapped as:
- 1 -> 0.0
- 2 -> 0.25
- 3 -> 0.5
- 4 -> 0.75
- 5 -> 1.0
We are already consitently using criteria score mappings to values between 0 and 1, so this change aims for simplifying benchmark results.
=> Normalize llm judge bench target variable
