IBM/unitxt

- .github/workflows/pipy.yml
- setup.py
git tag 0.0.1
git push origin --tags
> Add action for release new version to pypi by pushing a tag:

- src/unitxt/collections.py
- src/unitxt/dataset.py
- src/unitxt/fusion.py
- src/unitxt/metric.py
- src/unitxt/operator.py
- src/unitxt/operators.py
- src/unitxt/random_utils.py
- src/unitxt/split_utils.py
- src/unitxt/splitters.py
- src/unitxt/templates.py
- src/unitxt/test_utils/operators.py
- tests/test_operators.py
- tests/test_random_utils.py
Add context manager for reproducible randomization in radom_utils and edit all the files to use it
> Add reproducible randomization

- setup.cfg
> Revert "Fix typo"

- src/unitxt/split_utils.py
- Add offending input
- Print alternative split when split not found
> Improve split error messages

- prepare/cards/copa.py
- prepare/cards/race.py
- src/unitxt/catalog/cards/copa.json
- src/unitxt/catalog/cards/race_all.json
- src/unitxt/catalog/cards/race_high.json
- src/unitxt/catalog/cards/race_middle.json
Added the two last rameswar datasets
> race and copa

- utils/format
> Exclude virtual env from format utility

- src/unitxt/standard.py
Improve verification for wrong recipe demos assignments with suitable errors
> Improve verification for recipe demos assignments

- src/unitxt/random_utils.py
- tests/test_random_utils.py
Default seed was not set, so initially each run
generated different selection.
Was less observed, because used of nested_seed() set the seed.
Also added unit test.
> Fixed bug in random initialization

- src/unitxt/task.py
- src/unitxt/templates.py
Assumed specific field name in part of the code.
> Fix multi label template bug

- src/unitxt/loaders.py
> Fixes slash in IBM COS

- prepare/cards/xwinogrande.py
- src/unitxt/catalog/cards/xwinogrande/en.json
- src/unitxt/catalog/cards/xwinogrande/jp.json
- src/unitxt/catalog/cards/xwinogrande/pt.json
- src/unitxt/catalog/cards/xwinogrande/ru.json
- src/unitxt/catalog/cards/xwinogrande/zh.json
- src/unitxt/operator.py
- src/unitxt/split_utils.py
- src/unitxt/splitters.py
- tests/test_loaders.py
- tests/test_recipe.py
Improved error messages when no train set is available
Fixed xwinograde
> Fix no train

- prepare/cards/belebele.py
- prepare/cards/openbookqa.py
- src/unitxt/catalog/cards/openbookQA.json
> Fixed belebele  so it will only test one langauge and fix path to openbookqa

- prepare/metrics/custom_f1.py
- src/unitxt/metrics.py
- src/unitxt/test_utils/metrics.py
(Currently only aggregates results (and not per class), so not too add too many scores.
> Add (micro/macro) precision and recall to CustomF1

- src/unitxt/test_utils/operators.py
- tests/test_operators.py
> Fixed operator compare

- src/unitxt/test_utils/card.py
When debug is false by not printing stream sizes.
(3x performance)
> Improve test card performance

- src/unitxt/operators.py
- tests/test_operators.py
- FilterByListsOfValues :  Filters a stream, yielding only instances that  whose field values are included in the specified values lists.
- Intersect  : Intersects the value of a field, which must be a list,  with a given list
- RemoveValues : Removes values in  of a field, which must be a list,  by a given list 
Added tests and improved error checks
> Added new operators

- src/unitxt/loaders.py
- tests/test_loaders.py
Hi, 
@yoavkatz has already approved the code modification.
Committing again just to pass the DCO test (signing my name).
> a fix for issue #286. committing again, now signed

- prepare/templates/classification/classification.py
- prepare/templates/classification/nli/templates.py
- src/unitxt/catalog/templates/classification/multi_class/default.json
- src/unitxt/catalog/templates/classification/nli/simple.json
- src/unitxt/register.py
- src/unitxt/test_utils/catalog.py
- tests/test_examples.py
- tests/test_hf_artifacts.py
- tests/test_preperation.py
- tests/test_randomization.py
- tests/test_templates.py
added for classification and nli 
"processors.take_first_non_empty_line",
"processors.lower_case_till_punc"
> added post processing

- src/unitxt/operators.py
> Make augmentation not affect test_randomization

- src/unitxt/operator.py
- src/unitxt/operators.py
- src/unitxt/splitters.py
- src/unitxt/test_utils/operators.py
- tests/test_operators.py
value in instrance operator and augmentors
> Added error message when failed to process

- src/unitxt/renderers.py
- src/unitxt/templates.py
- src/unitxt/text_utils.py
that receiveds a field with references, that should be a list of string.
Also added print out type in dictionary.
> Add support for multi reference template

- src/unitxt/artifact.py
- src/unitxt/dataset.py
- src/unitxt/operators.py
- tests/test_operators.py
This pull request is due to issues raised by Ilya Shnayderman and will be completed once his issues are solved.
> Improve filtering operator

- src/unitxt/loaders.py
Location is determined by IBM_COS_CACHE env var,
or by cwd if env var is not set.
Cache is enabled by default.
> Add caching to LoadFromIBMCos,

- docs/catalog.py
- src/unitxt/artifact.py
- src/unitxt/templates.py
- src/unitxt/test_utils/artifact.py
- src/unitxt/test_utils/metrics.py
- src/unitxt/test_utils/operators.py
(For readibily of multi-lingual artificats and metrics)
> Change calls to json.dumps to allow storing in non standard ascii

- src/unitxt/templates.py
format as dataclass parameters
> FIX multiple choice template

- prepare/tasks/translation/directed.py
- src/unitxt/catalog/tasks/translation/directed.json
change the translation metric from bleu to normalized_sacrebleu
> modify to different bleu impl.

- src/unitxt/version.py
New version equivalent to 1.4.0 , due to release process issue.
> Update version to 1.4.1

- prepare/metrics/normalized_sacrebleu.py
- prepare/metrics/unnormalized_sacrebleu.py
- requirements/base.rqr
- src/unitxt/catalog/metrics/normalized_sacrebleu.json
- src/unitxt/catalog/metrics/sacrebleu.json
- src/unitxt/metrics.py
- src/unitxt/test_utils/metrics.py
1. Added new requirement
2. Passed tokenize ja-mecab to metric
3. Renamed sacrebleu file to avoid name conflict with HF sacrebleu imports.
> Added support for Japanese in sacrebleu

- docs/docs/contributors_guide.rst
Add a section to the unitxt contributors guide which explains how to edit and test the unitxt docs.
Closes https://github.com/IBM/unitxt/issues/445
> Added instructions on how to update the unitxt docs

- prepare/cards/reuters21578.py
- prepare/cards/unfair_tos.py
- prepare/templates/classification/classification.py
- src/unitxt/catalog/cards/reuters21578/ModApte.json
- src/unitxt/catalog/cards/reuters21578/ModHayes.json
- src/unitxt/catalog/cards/reuters21578/ModLewis.json
- src/unitxt/catalog/cards/unfair_tos.json
- src/unitxt/catalog/templates/classification/multi_label/all.json
- src/unitxt/catalog/templates/classification/multi_label/default.json
- src/unitxt/catalog/templates/classification/multi_label/empty.json
And changes to multi label datasets
> New multi label template

- prepare/cards/unfair_tos.py
- src/unitxt/catalog/cards/unfair_tos.json
Choose demonstrations such that label are distributions are balanced.
> Balance demos in fair_tos datasets

- src/unitxt/operators.py
adjust `LengthBalancer` docstring so it looks better in RST docs
> Length balancer docstring

- prepare/templates/standard.py
- src/unitxt/catalog/templates/key_val_with_new_lines.json
- src/unitxt/ui/constants.py
- src/unitxt/ui/load_catalog_data.py
- src/unitxt/ui/run.py
some ui changes + new template
> Improve UI code presentation and organization

- prepare/cards/multidoc2dial.py
- src/unitxt/catalog/cards/multidoc2dial/abstractive.json
- src/unitxt/catalog/cards/multidoc2dial/extractive.json
abstractive and extractive versions of the multidoc2dial data (https://huggingface.co/datasets/multidoc2dial)
> Add multidoc2dial dataset in its abstractive and extractive forms

- src/unitxt/artifact.py
- tests/test_artifact.py
No need to have both Artifact.set_artifact_identifier() and the regular setter
> Remove set_artifact_identifier

- prepare/metrics/kendalltau.py
- src/unitxt/catalog/metrics/kendalltau_b.json
- src/unitxt/metrics.py
Add metric for Kendall's tau correlation coefficient
> Add Kendall's tau metric

- prepare/cards/unfair_tos.py
- prepare/templates/classification/classification.py
- src/unitxt/catalog/templates/classification/multi_label/default.json
- src/unitxt/catalog/templates/classification/multi_label/empty.json
- src/unitxt/metrics.py
- src/unitxt/test_utils/card.py
The use of lower_case_till_punc caused a bug that only first label in multi label was considered.
Also added debugging printout  to test_card which shows the output of post processors.
> Fix multi label classification template and improve debugging 

- examples/example3.py
- prepare/cards/20_newsgroups.py
- prepare/instructions/empty.py
- prepare/instructions/models/alpaca.py
- prepare/system_prompts/models/alpaca.py
- prepare/system_prompts/models/japanese_llama.py
- prepare/system_prompts/models/llama.py
- prepare/templates/classification/nli/templates.py
- src/unitxt/blocks.py
- src/unitxt/card.py
- src/unitxt/catalog/cards/20_newsgroups.json
- src/unitxt/catalog/instructions/empty.json
- src/unitxt/catalog/instructions/models/llama.json
- src/unitxt/catalog/system_prompts/models/alpaca.json
- src/unitxt/catalog/system_prompts/models/japanese_llama.json
- src/unitxt/catalog/system_prompts/models/llama.json
- src/unitxt/catalog/templates/classification/nli/simple_with_instruction_model_llama.json
- src/unitxt/dataset.py
- src/unitxt/formats.py
- src/unitxt/instructions.py
- src/unitxt/metric.py
- src/unitxt/prepare_utils/card_types.py
- src/unitxt/standard.py
- src/unitxt/system_prompts.py
- src/unitxt/templates.py
- tests/library/test_formats.py
- tests/library/test_operators.py
- tests/library/test_recipe.py
- tests/library/test_templates.py
the card runs all the way through, and completes with exitcode = 0.
> Migrate (task-related) Instruction into Template, and introduce (task independent) SystemPrompt

- prepare/cards/tab_fact.py
- src/unitxt/catalog/cards/tab_fact.json
* Added a new taskcard for Table Fact Checking using TabFact public dataset
* The dataset is loaded from ibm org HF hub(https://huggingface.co/datasets/ibm/tab_fact) where a custom dataset loading script is added to load dataset in appropriate format.
> Add tab_fact dataset, a dataset for classification of textual entailment from tables

- src/unitxt/operator.py
in the case the stream does not perorm any modification of the input
For #626
> Fix problem in process_instance

- src/unitxt/struct_data_operators.py
- tests/library/test_struct_data_operators.py
Added the following tabular data processing operators.
Table serialization operators:
- SerializeTableAsDFLoader -- Pandas dataframe based code snippet format table serializer
- SerializeTableAsJson -- JSON table serializer
These table representation formats are shown to perform well across tasks with LLMs in recent literature.
Table processing operators:
- ConvertTableColNamesToSequential -- Replaces table column names with static sequential names
- ShuffleTableRows -- Shuffles the input table rows randomly
- ShuffleTableColumns -- Shuffles the table columns randomly
These operators are to be utilized for evaluating the impact of row-invariance, column-invariance & header-row information of table structure on LLM performance for tabular data tasks.
> Add essential table processing operators

- prepare/processors/processors.py
- src/unitxt/catalog/processors/capitalize.json
- src/unitxt/catalog/processors/substring.json
- src/unitxt/processors.py
- tests/library/test_postprocessors.py
This adds more string processors.
Closes #608 .
> Add Capitalize and Substring operators.  Add tests.

- src/unitxt/templates.py
- tests/library/test_templates.py
Closes: https://github.com/IBM/unitxt/issues/642
> Seperate inputs processing and instruction processing in templates

- requirements/ui.rqr
- src/unitxt/metrics.py
Closes: https://github.com/IBM/unitxt/issues/596
> Add some operators requirements

- src/unitxt/parsing_utils.py
- tests/library/test_parsing_utils.py
- tests/library/test_recipe.py
Hopefully,  Closes: https://github.com/IBM/unitxt/issues/641
> more careful before rejecting queries

- src/unitxt/operators.py
- tests/library/test_operators.py
Added new operator `DuplicateInstances` which duplicates each instance in stream a given number of times
For: #681
> DuplicateInstances operator

- src/unitxt/metrics.py
- tests/library/test_metrics.py
Similar to "mean" reduction type but takes the "max".
> Allow max reduction type in metric to find the best overall score over all instances

- src/unitxt/settings_utils.py
- tests/library/test_settings.py
> Handle all env variables with expected types

- prepare/cards/coedit.py
- prepare/tasks/grammatical_error_correction.py
- prepare/templates/editing/grammatical_error_correction.py
- src/unitxt/catalog/cards/coedit_gec.json
- src/unitxt/catalog/tasks/grammatical_error_correction.json
- src/unitxt/catalog/templates/grammatical_error_correction/simple.json
> Grammatical error correction task

- docs/catalog.py
- prepare/cards/wikitq.py
- src/unitxt/artifact.py
- src/unitxt/catalog/cards/wikitq.json
> Add tags and descriptions for assets on the website

- src/unitxt/operators.py
- tests/library/test_operators.py
not only on keys in the instance
> Allow FilterByCondition to condition also on subfields

- src/unitxt/test_utils/card.py
To help debug and see the expected score are right.
> Add sample score output in test card

- src/unitxt/loaders.py
- tests/library/test_loaders.py
Added loader which can be used to load dictionaries as per #699
> Support for loading dictionaries

- docs/docs/adding_dataset.rst
- docs/docs/adding_metric.rst
- docs/docs/adding_task.rst
Review of unitxt documentation - adding more details and examples.
> Documentation review

- prepare/formats/models/llama3.py
- src/unitxt/catalog/formats/models/llama3.json
As described in https://huggingface.co/blog/llama3#how-to-prompt-llama-3, https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/
> Basic format for llama3 models

- docs/docs/adding_dataset.rst
Reviewing the text of Unitxt tutorials, editing language and minor formatting.
> Reviewing Unitxt tutorials

- prepare/cards/billsum.py
- src/unitxt/catalog/cards/billsum.json
BillSum, summarization of US Congressional and California state bills.
paper: https://aclanthology.org/D19-5406v1.pdf
HF page: https://huggingface.co/datasets/billsum?row=0
> Add billsum dataset

- prepare/tasks/ner.py
- src/unitxt/catalog/tasks/ner/all_entity_types.json
- src/unitxt/catalog/tasks/ner/single_entity_type.json
'text' was set to different types in input and outputs.
> Ner typing had a mistake.

- prepare/cards/safety/bbq.py
- prepare/cards/safety/discrim_eval.py
- src/unitxt/catalog/cards/safety/bbq/Age.json
- src/unitxt/catalog/cards/safety/bbq/Disability_status.json
- src/unitxt/catalog/cards/safety/bbq/Gender_identity.json
- src/unitxt/catalog/cards/safety/bbq/Nationality.json
- src/unitxt/catalog/cards/safety/bbq/Physical_appearance.json
- src/unitxt/catalog/cards/safety/bbq/Race_ethnicity.json
- src/unitxt/catalog/cards/safety/bbq/Race_x_SES.json
- src/unitxt/catalog/cards/safety/bbq/Race_x_gender.json
- src/unitxt/catalog/cards/safety/bbq/Religion.json
- src/unitxt/catalog/cards/safety/bbq/SES.json
- src/unitxt/catalog/cards/safety/bbq/Sexual_orientation.json
- src/unitxt/catalog/cards/safety/discrim_eval/explicit.json
- src/unitxt/catalog/cards/safety/discrim_eval/implicit.json
Implementation of select safety benchmarks used in the MLCommons AI Safety Benchmark (https://mlcommons.org/working-groups/ai-safety/ai-safety/).
Based on code at https://github.com/mlcommons/modelgauge.
Signed-off-by: Jonathan Bnayahu <bnayahu@il.ibm.com>
> Implementation of select safety benchmarks

- prepare/cards/safety/bbq.py
- prepare/cards/safety/discrim_eval.py
- prepare/cards/safety/simple_safety_tests.py
- src/unitxt/catalog/cards/safety/bbq/Age.json
- src/unitxt/catalog/cards/safety/bbq/Disability_status.json
- src/unitxt/catalog/cards/safety/bbq/Gender_identity.json
- src/unitxt/catalog/cards/safety/bbq/Nationality.json
- src/unitxt/catalog/cards/safety/bbq/Physical_appearance.json
- src/unitxt/catalog/cards/safety/bbq/Race_ethnicity.json
- src/unitxt/catalog/cards/safety/bbq/Race_x_SES.json
- src/unitxt/catalog/cards/safety/bbq/Race_x_gender.json
- src/unitxt/catalog/cards/safety/bbq/Religion.json
- src/unitxt/catalog/cards/safety/bbq/SES.json
- src/unitxt/catalog/cards/safety/bbq/Sexual_orientation.json
- src/unitxt/catalog/cards/safety/discrim_eval/explicit.json
- src/unitxt/catalog/cards/safety/discrim_eval/implicit.json
- src/unitxt/catalog/cards/safety/simple_safety_tests.json
Tags, descriptions, and data classifications for the safety datasets.
> Added tags and descriptions to safety cards

- src/unitxt/ui/load_catalog_data.py
- src/unitxt/ui/run.py
> Add view option for Task definitions in UI explorer.

- examples/evaluate_dataset.py
- examples/load_dataset.py
- examples/standalone_evaluation.py
- requirements/tests.rqr
- src/unitxt/utils.py
- tests/catalog/test_preparation.py
- tests/library/test_examples.py
Up to now, there were tests for examples in test_examples . but these were hard coded and not related to the examples/*.py
This PR runs the examples/*.py, like the test_preperations , by running the files.
> Moved test_examples to run the actual examples  

- docs/docs/examples.rst
- examples/qa_evaluation.py
To demos reuse of tasks and templates
Also added description on how to use public InferenceEngines
> Added example of open qa using catalog

- docs/docs/examples.rst
- prepare/cards/wnli.py
- src/unitxt/catalog/cards/wnli.json
- src/unitxt/catalog/cards/wnli/truthfulness.json
since WNLI is used in the demos -  simplified it , so each processing effects one field, and it used explicit splitting.
> Update example intro and simplified WNLI cards

- docs/docs/adding_dataset.rst
> docs: update adding_dataset.rst

- src/unitxt/text_utils.py
- tests/library/test_text_utils.py
as in recent prepare/cards/numeric_nlg
> prepare for __description__= that is different from those embedded automtically

- examples/qa_evaluation.py
- examples/standalone_qa_evaluation.py
- src/unitxt/text_utils.py
> Add ability to print_dict to print selected fields

- docs/docs/examples.rst
- examples/standalone_evaluation_llm_as_judge.py
- src/unitxt/artifact.py
- src/unitxt/catalog.py
- src/unitxt/dataset_utils.py
- src/unitxt/llm_as_judge.py
- src/unitxt/standard.py
- src/unitxt/utils.py
> Allow add-hoc metrics and template (and Add first version of standalone example of dataset with LLM as a judge )

- src/unitxt/inference.py
- tests/library/test_inference_engine.py
Signed-off-by: elronbandel <elron.bandel@ibm.com>
> Add option to lazy load hf inference engine and fix requirements mechanism

- prepare/cards/language_identification.py
- prepare/formats/models/starling.py
- prepare/metrics/code_mixing_detection.py
- prepare/tasks/language_identification.py
- prepare/templates/language_identification/language_identification.py
- src/unitxt/catalog/cards/language_identification.json
- src/unitxt/catalog/formats/models/starling.json
- src/unitxt/catalog/metrics/is_code_mixed.json
- src/unitxt/catalog/tasks/language_identification.json
- src/unitxt/catalog/templates/language_identification/all.json
- src/unitxt/catalog/templates/language_identification/simple.json
- src/unitxt/metrics.py
- Metric that utilizes generative LLM to estimate if a text is code-mixed
- Added language identification task + example card
- Format for Starling LM
> Code mixing metric

- docs/docs/examples.rst
- docs/docs/saving_and_loading_from_catalog.rst
- examples/evaluate_different_templates.py
- src/unitxt/standard.py
- tests/library/test_examples.py
Added a new example to compare templates and improved look of example page
> Example improvements

- examples/evaluate_different_formats.py
- examples/evaluate_different_templates.py
- examples/evaluation_summarization_dataset_llm_as_judge.py
- examples/inference_using_ibm_watsonx_ai.py
- examples/qa_evaluation.py
- examples/standalone_evaluation_llm_as_judge.py
- examples/standalone_qa_evaluation.py
- prepare/metrics/llm_as_judge/llamaguard.py
- prepare/metrics/llm_as_judge/rating/llama_3_ibm_genai_generic_template.py
- prepare/metrics/llm_as_judge/rating/llama_3_ibm_genai_mt_bench_template.py
- src/unitxt/artifact.py
- src/unitxt/catalog/metrics/llm_as_judge/rating/llama_3_70b_instruct_ibm_genai_template_generic_single_turn.json
- src/unitxt/catalog/metrics/llm_as_judge/rating/llama_3_70b_instruct_ibm_genai_template_generic_single_turn_with_reference.json
- src/unitxt/catalog/metrics/llm_as_judge/rating/llama_3_70b_instruct_ibm_genai_template_mt_bench_single_turn.json
- src/unitxt/catalog/metrics/llm_as_judge/rating/llama_3_8b_instruct_ibm_genai_template_mt_bench_single_turn.json
- src/unitxt/catalog/metrics/llm_as_judge/safety/llama_3_70b_instruct_ibm_genai_template_unsafe_content.json
- src/unitxt/catalog/metrics/llm_as_judge/safety/llama_3_8b_instruct_ibm_genai_template_unsafe_content.json
- src/unitxt/dataclass.py
- src/unitxt/inference.py
- tests/library/test_dataclass.py
Added additional inference parameters for both `IbmGenAiInferenceEngine` and `OpenAiInferenceEngine`
> Additional inference parameters for openai and genai

- prepare/cards/billsum.py
- prepare/cards/tldr.py
- src/unitxt/catalog/cards/billsum.json
- src/unitxt/catalog/cards/billsum_document_filtered_to_10000_chars.json
- src/unitxt/catalog/cards/billsum_document_filtered_to_6000_chars.json
- src/unitxt/catalog/cards/tldr.json
- src/unitxt/catalog/cards/tldr_document_filtered_to_10000_chars.json
- src/unitxt/catalog/cards/tldr_document_filtered_to_6000_chars.json
(shuffled by the SplitRandomMix)
> add validation to tldr, remove shuffle from billsum

- docs/docs/introduction.rst
Signed-off-by: welisheva22 <welisheva22@gmail.com>
> Update introduction.rst - - copy edits (grammar, consistency, clarity)

- .secrets.baseline
- src/unitxt/metrics.py
- tests/library/test_metrics.py
A suggested patch for issue #1059
> suggested patch for score_ci inconsistency issue

- docs/docs/adding_format.rst
> Fix link to llama blog in adding_format.rst

- .secrets.baseline
- src/unitxt/error_utils.py
- src/unitxt/metrics.py
- tests/library/test_operators.py
for issue https://github.com/IBM/unitxt/issues/1069
> warn before score overwrite

- src/unitxt/artifact.py
- src/unitxt/collections_operators.py
- src/unitxt/generator_utils.py
- src/unitxt/loaders.py
- src/unitxt/metric_utils.py
- src/unitxt/metrics.py
- src/unitxt/operators.py
- src/unitxt/splitters.py
- src/unitxt/stream.py
- src/unitxt/struct_data_operators.py
- src/unitxt/utils.py
Signed-off-by: elronbandel <elron.bandel@ibm.com>
> Add central controllable deepcopy function

- .pre-commit-config.yaml
- docs/docs/adding_dataset.rst
- docs/docs/examples.rst
- docs/docs/saving_and_loading_from_catalog.rst
- examples/evaluate_different_demo_selections.py
- examples/evaluate_different_formats.py
- examples/evaluate_existing_dataset_by_llm_as_judge.py
- examples/evaluate_existing_dataset_no_install.py
- examples/evaluate_existing_dataset_with_install.py
- examples/evaluate_summarization_dataset_llm_as_judge.py
- examples/standalone_qa_evaluation.py
- tests/library/test_examples.py
> Improve examples

- docs/docs/production.rst
Changed "End to End" to "End-to-End"
> Update production.rst ---- add hyphens

- docs/docs/demo.rst
added the word "the" in the documentation
> Update demo.rst - minor copy change

- src/unitxt/card.py
> Update card.py - minor documentation changes

- src/unitxt/deprecation_utils.py
For issue [#1199](https://github.com/IBM/unitxt/issues/1199)
Adding a decorator that raises warning with message, that certain class has been initialised.
> add decorator with init warning

- src/unitxt/inference.py
Add `TogetherAiInferenceEngine`, which uses the [Together AI API](https://docs.together.ai/) for inference.
> Add TogetherAiInferenceEngine

- src/unitxt/formats.py
- src/unitxt/schema.py
- tests/library/test_api.py
- tests/library/test_benchmark.py
- tests/library/test_formats.py
- tests/library/test_recipe.py
Closes: https://github.com/IBM/unitxt/issues/1202
> Add demos to task_data

- .secrets.baseline
- src/unitxt/metrics.py
- tests/library/test_metrics.py
A suggested PR for issue #1214: fixed a bug in score_prefix for grouped instance scores
> A suggested PR for issue #1214: fixed a bug in score_prefix for grouped instance scores

- .secrets.baseline
- src/unitxt/metrics.py
1.allow global metric ci computation for scores other than main
2.bugfix in retrievalatk
> CI for metrics other than main + Bugfix in RetrievalAtK

- .github/workflows/test_helm.yml
- prepare/metrics/prediction_length.py
- requirements/helm.rqr
- src/unitxt/catalog/metrics/prediction_length.json
- src/unitxt/metrics.py
Adding a simple metric that return the length of the prediction.
> Add prediction length metric

- prepare/metrics/rag_faithfulness.py
- src/unitxt/catalog/metrics/rag/faithfulness.json
- src/unitxt/catalog/metrics/rag/faithfulness/bert_score_k_precision.json
- src/unitxt/catalog/metrics/rag/faithfulness/bert_score_k_precision_ml.json
- src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert_bge.json
- src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert_mini_lm.json
- src/unitxt/catalog/metrics/rag/faithfulness/token_k_precision.json
This is the same fix as in https://github.com/IBM/unitxt/pull/1256,
but for rag faithfulness instead of answer_correctness
> Fix faithfulness confidence intervals

- .secrets.baseline
- prepare/metrics/rag.py
- prepare/metrics/rag_answer_correctness.py
- prepare/metrics/rag_context_correctness.py
- prepare/metrics/rag_faithfulness.py
- src/unitxt/catalog/metrics/rag/answer_correctness.json
- src/unitxt/catalog/metrics/rag/answer_correctness/bert_score_recall.json
- src/unitxt/catalog/metrics/rag/answer_correctness/bert_score_recall_ml.json
- src/unitxt/catalog/metrics/rag/answer_correctness/sentence_bert_bge.json
- src/unitxt/catalog/metrics/rag/answer_correctness/sentence_bert_mini_lm.json
- src/unitxt/catalog/metrics/rag/answer_correctness/token_recall.json
- src/unitxt/catalog/metrics/rag/context_correctness.json
- src/unitxt/catalog/metrics/rag/context_correctness/map.json
- src/unitxt/catalog/metrics/rag/context_correctness/mrr.json
- src/unitxt/catalog/metrics/rag/context_correctness/retrieval_at_k.json
- src/unitxt/catalog/metrics/rag/faithfulness.json
- src/unitxt/catalog/metrics/rag/faithfulness/bert_score_k_precision.json
- src/unitxt/catalog/metrics/rag/faithfulness/bert_score_k_precision_ml.json
- src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert_bge.json
- src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert_mini_lm.json
- src/unitxt/catalog/metrics/rag/faithfulness/token_k_precision.json
- src/unitxt/catalog/metrics/token_overlap_with_context.json
- src/unitxt/metrics.py
- src/unitxt/operators.py
Metric pipeline copy only the score, resulting in wrong metric name and confidence interval which are not copied. This pr fix this.
> A fix for a bug in metric pipeline

- prepare/cards/tablebench.py
- src/unitxt/catalog/cards/tablebench.json
Added Tablebench(https://tablebench.github.io/) taskcard. It is a comprehensive and complex dataset for evaluating LLMs on Table Question Answering task.
> Added Tablebench taskcard

- src/unitxt/struct_data_operators.py
- tests/library/test_struct_data_operators.py
Adds following robustness check operators for tables.
- TransposeTable - Transpose the table by converting rows as columns and vice versa
- DuplicateTableRows - Duplicates specific rows of a table for the given number of times.
- DuplicateTableColumns - Duplicates specific columns of a table for the given number of times.
- InsertEmptyTableRows - Inserts empty rows in a table at random locations for the given number of times.
Additionally, adds a new table serializer for modeling tabular data in HTML format.
Tests added and verified for all of them.
> add operators for robustness check on tables

- prepare/recipes/bluebench.py
- src/unitxt/catalog/recipes/bluebench/safety/attaq_500.json
change 'max_test_instances' for bluebench.recipe.attaq_500 from 10 to 100
> change the max_test_instances of bluebench.recipe.attaq_500 to 100

- docs/docs/examples.rst
- docs/docs/glossary.rst
- docs/docs/tutorials.rst
- docs/docs/types_and_serializers.rst
- examples/custom_type.py
For: https://github.com/IBM/unitxt/issues/1283
Closes: https://github.com/IBM/unitxt/issues/1283
> Add documentation for types and serializers

- docs/docs/llm_as_judge.rst
closes: https://github.com/IBM/unitxt/issues/1332
> A swifty PR suggested for issue #1332

- docs/catalog.py
- src/unitxt/text_utils.py
> Print catalog entries as yamls

- prepare/engines/classification/classification_engines.py
- src/unitxt/catalog/engines/classification/llama_3_405b_instruct_wml.json
Signed-off-by: lilacheden <lilach.edel@gmail.com>
> add llama-3-405b-instruct wml classification engine

- src/unitxt/settings_utils.py
Copy of https://github.com/IBM/unitxt/pull/1386/files but in a branch
> Fix package dir in settings

- prepare/augmentors/text_augmentors.py
- src/unitxt/catalog.py
- src/unitxt/catalog/augmentors/augment_whitespace_prefix_and_suffix_task_input.json
- src/unitxt/catalog/augmentors/augment_whitespace_task_input.json
- tests/library/test_artifact.py
closes: https://github.com/IBM/unitxt/issues/1396
> added 'add_link_to_catalog' for easily adding artifact_links with/without deprecation msg

- .github/workflows/catalog_preparation.yml
- prepare/metrics/rag_granite_guardian.py
- pyproject.toml
- src/unitxt/catalog/metrics/rag/granite_guardian_answer_relevance.json
- src/unitxt/catalog/metrics/rag/granite_guardian_context_relevance.json
- src/unitxt/catalog/metrics/rag/granite_guardian_groundedness.json
- src/unitxt/metrics.py
- utils/.secrets.baseline
Following code examples from the [recipes](https://github.com/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/Granite_Guardian/), and integration with watsonx by @martinscooper
> Granite Guardian RAG metrics

- src/unitxt/card.py
- src/unitxt/deprecation_utils.py
- src/unitxt/dialog_operators.py
- src/unitxt/error_utils.py
- src/unitxt/image_operators.py
- src/unitxt/inference.py
- src/unitxt/loaders.py
- src/unitxt/metric_utils.py
- src/unitxt/metrics.py
- src/unitxt/operator.py
- src/unitxt/operators.py
- src/unitxt/span_lableing_operators.py
- src/unitxt/task.py
- src/unitxt/templates.py
- utils/.secrets.baseline
facelift for the following webpages,  all through indentations inside docstrings:
https://www.unitxt.ai/en/latest/unitxt.card.html#unitxt.card.TaskCard
https://www.unitxt.ai/en/latest/unitxt.deprecation_utils.html#unitxt.deprecation_utils.compare_versions
https://www.unitxt.ai/en/latest/unitxt.dialog_operators.html#unitxt.dialog_operators.SerializeDialog
https://www.unitxt.ai/en/latest/unitxt.dialog_operators.html#unitxt.dialog_operators.SerializeOpenAiFormatDialog
https://www.unitxt.ai/en/latest/unitxt.error_utils.html#unitxt.error_utils.UnitxtWarning
https://www.unitxt.ai/en/latest/unitxt.error_utils.html#unitxt.error_utils.UnitxtError
https://www.unitxt.ai/en/latest/unitxt.image_operators.html#unitxt.image_operators.PixelNoise …
> simplify class parameter listing on web page

- .github/workflows/library_tests.yml
- README.md
- pyproject.toml
> Fix coverage tests

- .github/workflows/performance.yml
Otherwise metrics use inference.
> Add UNITXT_MOCK_INFERENCE_MODE environment variable to performance workflow

- src/unitxt/task.py
- tests/library/test_artifact.py
Closes: https://github.com/IBM/unitxt/issues/1514
> Verify metrics prediction_type without loading metric

- docs/docs/examples.rst
- examples/evaluate_with_custom_metric.py
- examples/standalone_qa_evaluation.py
Also improve standalone_qa_evaluation output and doc.
> Added example of custom metric

- README.md
- prepare/cards/ag_news.py
- prepare/cards/sst2.py
- prepare/cards/wnli.py
- src/unitxt/catalog/cards/ag_news.json
- src/unitxt/catalog/cards/sst2.json
- src/unitxt/catalog/cards/wnli.json
- src/unitxt/catalog/cards/wnli/truthfulness.json
- src/unitxt/inference.py
- src/unitxt/loaders.py
- src/unitxt/metrics.py
- tests/library/test_loaders.py
- utils/.secrets.baseline
Update ag news to be loaded and tested faster
> Update few slow datasets

- prepare/cards/safety/xstest.py
- src/unitxt/catalog/cards/safety/xstest.json
- src/unitxt/catalog/metrics/llm_as_judge/direct/criteria/assistant_message_compliance.json
- src/unitxt/llm_as_judge_constants.py
* Implementation of XSTest, for identifying exaggerated Safety behaviors
* Added Compliance judge criteria, to measure compliance/refusal with the user's message.
> XSTest (and compliance criteria)

- src/unitxt/metrics.py
- tests/library/test_metrics.py
so it is 0 if no arguments in predictions but some argument in references,
Made treatment of flattening dictionaries more robust. 
Added documentation
Added unit tests.
> Fixed argument_value_precision

- prepare/cards/judge_bench/toxic_chat_jailbreak.py
- prepare/cards/judge_bench/toxic_chat_toxicity.py
- src/unitxt/base_metric.py
- src/unitxt/catalog/cards/judege_bench/toxic_chat/jailbreaking.json
- src/unitxt/catalog/cards/judege_bench/toxic_chat/toxicity.json
- src/unitxt/catalog/metrics/llm_as_judge/direct/criteria/toxicity.json
- src/unitxt/dataset.py
- src/unitxt/inference.py
- src/unitxt/llm_as_judge_constants.py
- src/unitxt/metric.py
- src/unitxt/metrics.py
This PR add the first LLM as a Judge benchmark cards. It does so by using the new MetricInferenceEngine.
> LLM judge judgebench benchmarks

- prepare/metrics/llm_as_judge/pairwise_rating/llama_3_arena_hard_template.py
- src/unitxt/catalog/metrics/llm_as_judge/pairwise_comparative_rating/llama_3_3_70b_instruct/template_arena_hard.json
update the token limit so the judge can get to the actual rating.
> Arena hard fix
